name: Run Shopify Script

on:
  schedule:
    # Runs at 7am, 9am, 11am, 1pm, 3pm, and 5pm EST
    # You need to convert these times to UTC
    - cron:  '0 11,13,15,17,19,21 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run the script
      env:
        SHOPIFY_DOMAIN: ${{secrets.SHOPIFY_DOMAIN }}
        SHOPIFY_API_KEY: ${{secrets.SHOPIFY_API_KEY }}
        SHOPIFY_API_SECRET_KEY: ${{secrets.SHOPIFY_API_SECRET_KEY }}
        SHOPIFY_ACCESS_TOKEN: ${{secrets.SHOPIFY_ACCESS_TOKEN }}
        SHOPIFY_API_SCOPES: ${{secrets.SHOPIFY_API_SCOPES }}
        SHOPIFY_LOCATION_ID: ${{secrets.SHOPIFY_LOCATION_ID }}
        FTP_HOST: ${{secrets.FTP_HOST }}
        FTP_USER: ${{secrets.FTP_USER }}
        FTP_PASSWORD: ${{secrets.FTP_PASSWORD }}
      run: node index.js # Replace with the path to your script

